### ISSUE TITLE
Beta Annealing Question

### ISSUE THREAD

**Issue by oliverc1623** [Howuhh/prioritized_experience_replay#2]
Hello! 

Nice work on your PER implementation. I have a question. Why does your implementation not feature beta annealing for the Prioritized Replay Buffer? Some insight on this decision would be greatly appreciated!

**Comment by Howuhh** [comment]
Hi! The reason is very simple. I don't relate this to implementing PER specifically, it's a hyperparameter of a method that will use PER, so it didn't seem necessary for me to implement it. The fact that there is a small demonstration of DQN here is just a test that PER works, regardless of more complex methods. After all, this implementation is primarily for education purposes.
